version: '3'

volumes:
    db-data:

services:
    web:
        build: .
        command: bundle exec puma -C /GCBGB/config/puma.rb
        ports: 
            - '3000:3000'
        volumes:
            - '.:/ryo1-app'
        environment:
            RAILS_ENV: 'production'
        environment:
             - 'DATABASE_PASSWORD=postgres'
             - 'POSTGRES_PASSWORD=postgres'
        tty: true
        stdin_open: true
        depends_on:
            - db
        links:
            - db
        environment: 
          - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
          - 'DATABASE_PASSWORD=postgres'
    selenium_chrome:
      image: selenium/standalone-chrome-debug
      logging:
        driver: none
        


    db:
        image: postgres
        volumes:
            - 'db-data:/var/lib/postgresql/data'
        environment:
            - 'DATABASE_PASSWORD=postgres'
            - 'POSTGRES_PASSWORD=postgres'
            - 'POSTGRES_HOST_AUTH_METHOD=trust'

    nginx:
        build: containers/nginx
        ports:
          - "80:80"
        volumes_from:
          - web
        depends_on:
          - web




 
